"""Emit config/generated.mk from declarative task registry.

Reads task definitions from ``config/tasks.toml`` and writes one phony Make
target per task in the active profile. Each recipe delegates to
``poetry run python -m <module>``.

Usage
-----
Generate::

    python -m part_io.cli.generate.tasks

Generate for a profile::

    python -m part_io.cli.generate.tasks --profile strict

Check freshness (CI)::

    python -m part_io.cli.generate.tasks --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from part_io.adapters.config.task_registry_loader import load_registry, tasks_for_profile
from part_io.models.registry import TaskSpec

_OUTPUT = Path("config/generated.mk")

_HEADER = """\
# AUTO-GENERATED by `python -m part_io.cli.generate.tasks` — do not edit by hand.
# Regenerate : part_io-tasks generate-tasks
# Check      : part_io-tasks check-tasks
"""


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------


def discover_tasks(profile: str | None = None) -> list[TaskSpec]:
    """Return registry-backed CLI tasks for *profile* or default profile."""
    registry = load_registry()
    return tasks_for_profile(registry, profile=profile)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _render(tasks: list[TaskSpec]) -> str:
    """Return the full content of generated.mk for *tasks*."""
    lines: list[str] = [_HEADER, "\n"]

    # Aggregate variable for task runners that dispatch all declared lint targets.
    task_list = "".join(f" \\\n    {t.target}" for t in tasks)
    lines.append(f"TASK_TARGETS :={task_list}\n\n")

    # Single .PHONY declaration for all generated targets.
    lines.append(".PHONY: " + " ".join(t.target for t in tasks) + "\n\n")

    # One recipe per task with a help comment for build-tool integrations.
    for task in tasks:
        lines.append(f"{task.target}: ## {task.description}\n")
        lines.append(f"\tpoetry run python -m {task.module}\n")
        lines.append("\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------


def main() -> None:
    """Load registry tasks and write or verify config/generated.mk."""
    parser = argparse.ArgumentParser(
        description="Generate config/generated.mk from config/tasks.toml definitions."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when config/generated.mk is missing or stale.",
    )
    parser.add_argument(
        "--profile",
        help="Registry profile to generate or check task targets for.",
    )
    args = parser.parse_args()

    try:
        tasks = discover_tasks(profile=args.profile)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(2)

    content = _render(tasks)

    if args.check:
        if not _OUTPUT.exists():
            print(
                f"FAIL: {_OUTPUT} is missing — run: part_io-tasks generate-tasks",
                file=sys.stderr,
            )
            sys.exit(1)
        if _OUTPUT.read_text(encoding="utf-8") != content:
            print(
                f"FAIL: {_OUTPUT} is stale — run: part_io-tasks generate-tasks",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"OK: {_OUTPUT} is up to date ({len(tasks)} task(s)).")
        return

    _OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {len(tasks)} task(s) to {_OUTPUT}:")
    for task in tasks:
        print(f"  {task.target:<24}  {task.description}")


if __name__ == "__main__":
    main()
